services:
  vault:
    build: .
    container_name: dev-vault
    ports:
      - "8200:8200"
    environment:
      VAULT_LOCAL_CONFIG: |
        {
          "listener": [{"tcp": {"address": ":8200", "tls_disable": true}}],
          "storage": {"file": {"path": "/vault/data"}},
          "ui": true
        }
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_ADDR: "http://127.0.0.1:8200"
      OIDC_DISCOVERY_URL: "<your-oidc-discovery-url>"
      OIDC_CLIENT_ID: "<your-oidc-client-id>"
      OIDC_CLIENT_SECRET: "<your-oidc-client-secret>"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault-config.hcl:/vault/config/vault-config.hcl:ro
      - vault-data:/vault/data
      - ./setup-oidc.sh:/setup-oidc.sh:ro
    entrypoint:
      - /bin/sh
      - -c
      - |
        vault server -config=/vault/config/vault-config.hcl &
        sleep 5
        sh /setup-oidc.sh
        tail -f /dev/null
volumes:
  vault-data:
