      - name: Debug before Vault fetch
        run: |
          echo "== ENVIRONMENT BEFORE VAULT FETCH =="
          env
          ps aux
          curl -v http://127.0.0.1:8200/v1/sys/health || echo "Vault not reachable"
# Trigger reload for workflow_dispatch recognition
name: Build and Deploy to WildFly

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

  - name: Fetch secrets from Vault (OIDC)
      - name: Debug after Vault fetch
        run: |
          echo "== ENVIRONMENT AFTER VAULT FETCH =="
          env
          ps aux
          curl -v http://127.0.0.1:8200/v1/sys/health || echo "Vault not reachable"
        uses: hashicorp/vault-action@v2
        with:
          url: http://127.0.0.1:8200
          method: jwt
          role: github-actions
          secrets: |
            secret/data/wildfly WILDFLY_USER | WILDFLY_USER;
            secret/data/wildfly WILDFLY_PASS | WILDFLY_PASS;

      - name: Deploy to WildFly
        run: mvn wildfly:deploy
        env:
          WILDFLY_USER: ${{ env.WILDFLY_USER }}
          WILDFLY_PASS: ${{ env.WILDFLY_PASS }}
