# Fibonacci Test Workflow v1.0.0  
# Version: 1.0.0
# Created: 2024-01-26
# Purpose: Test fibonacci computation with versioning

name: Fibonacci Test v1.0.0

on:
  workflow_dispatch:
    inputs:
      iterations:
        description: 'Number of fibonacci numbers to compute'
        required: false
        default: '10'
        type: string

jobs:
  fibonacci:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Run fibonacci computation
      run: |
        echo "=== Fibonacci Test Workflow v1.0.0 ==="
        echo "Computing ${{ inputs.iterations }} fibonacci numbers..."
        echo "Workflow version: 1.0.0"
        
        # Simple fibonacci in bash
        n=${{ inputs.iterations }}
        a=0
        b=1
        echo "Fibonacci sequence:"
        echo "0: $a"
        echo "1: $b"
        
        for ((i=2; i<n; i++)); do
          c=$((a + b))
          echo "$i: $c"
          a=$b
          b=$c
        done
        
    - name: Workflow completion
      run: |
        echo "Fibonacci computation completed"
        echo "Version: 1.0.0"
        echo "Status: SUCCESS"