name: Test Validation Workflow

on:
  workflow_dispatch:
    inputs:
      test_param:
        description: 'Test parameter'
        required: true

jobs:
  test-job:
    runs-on: self-hosted
    steps:
      - name: Test Step
        run: |
          echo "Testing validation workflow"
          echo "Parameter: ${{ github.event.inputs.test_param }}"
          echo "✅ Validation test completed"